### PR TITLE
clarified spelling and description for autoPROC

### PR DESCRIPTION
**Pull request by CV-GPhL**
Corrected spelling and used similar description to other automated data processing pipelines.

### CODE REVIEW

**Comment by epeisach** [comment]
I agree with the roles expansion, as this is used by the deposition system, I question the changing of your program name. According to the Global Phasing website https://www.globalphasing.com/autoproc/manual/, autoPROC is the correct capitalization. Is Global Phasing changing the name of this suite?

**Comment by CV-GPhL** [comment]
autoPROC is the correct spelling - but as far as I can see we currently have "AutoPROC" (captital A at beginning) in base/mmcif_pdbx-base.dic, right? Or am I missing (or messed up) something?

**Comment by berrisfordjohn** [comment]
We will have to check and correct existing PDB entries as changing the case will mean that entries with AutoPROC will not validate in deposition - likely then depositors will just select another piece of software which is not what you want to happen.

**Comment by CV-GPhL** [comment]
From our side, depositors would have had either a PDB file (with all upper-case AUTOPROC) or a mmCIF file (with correct autoPROC spelling) for automatic harvesting/deposition. So any existing entry would have the "AutoPROC" spelling either because some software (unknown to us) is preparing mmCIF files with the different spelling or because the depositor selected the AutoPROC item from the OneDep pull-down menu ... right?

Sorry that we didn't notice this small difference earlier, but because we never used it that way we didn't think to check the dictionary for it. There might even be a historic confusion with a tool developed at the Canadian Light Source (CLS) that was called "AutoPROC" (not sure about upper/lower case handling) initially and is now renamed to AutoProcess to avoid the name clash with our software.

Anyway, it's probably partly our own fault for picking a not very distinctive name and spelling I guess ... and I can see changing existing entries causes definite problems, yes.

**Comment by epeisach** [comment]
I'm sorry - I read the diff backwards.  It should be lower case.  

This would affect ~670 entries which we can slowly correct.

It was probably inadvertantly put in with a capital "A" when first introduced to the dictionary as the requestor did not know about the capitalization.

So - yes we should fix this and slowly correct the entries.

**Pull request merged**
