### PR TITLE
Alises to Diamond Light Source VMX beamlines

### PR DESCRIPTION
**Pull request by graeme-winter**
I02-1 is VMXm
I02-2 is VMXi

This was identified as part of our efforts to clean up the NeXus format header files to meet the gold standard.

### CODE REVIEW

**Comment by graeme-winter** [comment]
Am happy that this rests for a while, to give me a chance to get up to speed with what is happening behind the scenes.

**Comment by epeisach** [comment]
Is VMXi and VMXm officially changing their names?

We do not generally add "common" names for a beamline unless the official name changes - as it will eventually cause confusion for the end user - and even the beamline when they are trying to justify their existence to funding agencies. At some point they will want a list of all structures solved at their site - and there will be multiple things to lookup.

For instance, if you go to https://www.diamond.ac.uk/Instruments/Mx/VMXi.html

the menu across the top lists VMXi and VMXm.

Was IO2 split into two beam lines?

we will need to contact the site-contact to ask them what the official name should be.  I will have our maintainer of biosync handle that.

**Comment by graeme-winter** [comment]
i02 was indeed split into two beamlines - i02-1 and i02-2 that were both part of the VMX beamline upgrade, and then called VMXi and VMXm. So the funny thing here is that you _have_ the common names for the beamlines but not the "machine name"

However, if you don't have an option to have an alias then keeping them as they are is better than changing (and I am not the person to ask for a _change_) it just means that we will have to sometimes use the "common name" and other times use the "machine name" when writing out gold standard data.

**Comment by epeisach** [comment]
Either way we need clarification. We only have one of VMXm and VMXi.

As their page indicates lower down something like "IO2-1 VMXi" (I might 1/2 mixed up) - that might be a perfectly good name. End users would have no confusion.  If they collect data - they might know IO2-1 or then might know VMXi.

Either way - biosync should have up to date information - so I asked the person maintaining biosync to write to the beamline and see what they want to be know for.

**Pull request closed without merging**
